version: '3'

services:
  postgres:
    image: postgres:13
    container_name: todoapp_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: todoapp_db
      POSTGRES_USER: todoapp_user
      POSTGRES_PASSWORD: pass123
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
